# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/amami/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/amami/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/amami/proprietary/lib/libcald_client.so:system/lib/libcald_client.so \
    vendor/sony/amami/proprietary/lib/libcald_pal.so:system/lib/libcald_pal.so \
    vendor/sony/amami/proprietary/lib/libcald_server.so:system/lib/libcald_server.so \
    vendor/sony/amami/proprietary/lib/libcald_util.so:system/lib/libcald_util.so \
    vendor/sony/amami/proprietary/lib/libcameralight.so:system/lib/libcameralight.so \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/cam_ctrl.dat:system/vendor/camera/LGI02BN1/cam_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/cap_ctrl.dat:system/vendor/camera/LGI02BN1/cap_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/chokoball.dat:system/vendor/camera/LGI02BN1/chokoball.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/color_ctrl.dat:system/vendor/camera/LGI02BN1/color_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/dataflow.dat:system/vendor/camera/LGI02BN1/dataflow.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/debug_mgr.dat:system/vendor/camera/LGI02BN1/debug_mgr.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/exposure_ctrl.dat:system/vendor/camera/LGI02BN1/exposure_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/face_detector.dat:system/vendor/camera/LGI02BN1/face_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/flicker_detector.dat:system/vendor/camera/LGI02BN1/flicker_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/focus_stats_conv.dat:system/vendor/camera/LGI02BN1/focus_stats_conv.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/hal_ctrl.dat:system/vendor/camera/LGI02BN1/hal_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/hal_ctrl_platform.dat:system/vendor/camera/LGI02BN1/hal_ctrl_platform.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/hdr_comp.dat:system/vendor/camera/LGI02BN1/hdr_comp.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/idt_ctrl.dat:system/vendor/camera/LGI02BN1/idt_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/image_conv.dat:system/vendor/camera/LGI02BN1/image_conv.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/imgproc.dat:system/vendor/camera/LGI02BN1/imgproc.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/jpeg_enc.dat:system/vendor/camera/LGI02BN1/jpeg_enc.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/lens_ctrl.dat:system/vendor/camera/LGI02BN1/lens_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/module.dat:system/vendor/camera/LGI02BN1/module.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/motion_estimation.dat:system/vendor/camera/LGI02BN1/motion_estimation.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/multiframe_nr.dat:system/vendor/camera/LGI02BN1/multiframe_nr.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/object_tracker.dat:system/vendor/camera/LGI02BN1/object_tracker.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/scene_detector.dat:system/vendor/camera/LGI02BN1/scene_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/snapshot_ctrl.dat:system/vendor/camera/LGI02BN1/snapshot_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1/streaming_ctrl.dat:system/vendor/camera/LGI02BN1/streaming_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1_IMX132.dat:system/vendor/camera/LGI02BN1_IMX132.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/cam_ctrl.dat:system/vendor/camera/SEM02BN1/cam_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/cap_ctrl.dat:system/vendor/camera/SEM02BN1/cap_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/chokoball.dat:system/vendor/camera/SEM02BN1/chokoball.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/color_ctrl.dat:system/vendor/camera/SEM02BN1/color_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/dataflow.dat:system/vendor/camera/SEM02BN1/dataflow.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/debug_mgr.dat:system/vendor/camera/SEM02BN1/debug_mgr.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/exposure_ctrl.dat:system/vendor/camera/SEM02BN1/exposure_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/face_detector.dat:system/vendor/camera/SEM02BN1/face_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/flicker_detector.dat:system/vendor/camera/SEM02BN1/flicker_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/focus_stats_conv.dat:system/vendor/camera/SEM02BN1/focus_stats_conv.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/hal_ctrl.dat:system/vendor/camera/SEM02BN1/hal_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/hal_ctrl_platform.dat:system/vendor/camera/SEM02BN1/hal_ctrl_platform.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/hdr_comp.dat:system/vendor/camera/SEM02BN1/hdr_comp.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/idt_ctrl.dat:system/vendor/camera/SEM02BN1/idt_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/image_conv.dat:system/vendor/camera/SEM02BN1/image_conv.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/imgproc.dat:system/vendor/camera/SEM02BN1/imgproc.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/jpeg_enc.dat:system/vendor/camera/SEM02BN1/jpeg_enc.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/lens_ctrl.dat:system/vendor/camera/SEM02BN1/lens_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/module.dat:system/vendor/camera/SEM02BN1/module.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/motion_estimation.dat:system/vendor/camera/SEM02BN1/motion_estimation.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/multiframe_nr.dat:system/vendor/camera/SEM02BN1/multiframe_nr.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/object_tracker.dat:system/vendor/camera/SEM02BN1/object_tracker.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/scene_detector.dat:system/vendor/camera/SEM02BN1/scene_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/snapshot_ctrl.dat:system/vendor/camera/SEM02BN1/snapshot_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1/streaming_ctrl.dat:system/vendor/camera/SEM02BN1/streaming_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1_IMX132.dat:system/vendor/camera/SEM02BN1_IMX132.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/cam_ctrl.dat:system/vendor/camera/SOI20BS0/cam_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/cap_ctrl.dat:system/vendor/camera/SOI20BS0/cap_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/chokoball.dat:system/vendor/camera/SOI20BS0/chokoball.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/color_ctrl.dat:system/vendor/camera/SOI20BS0/color_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/dataflow.dat:system/vendor/camera/SOI20BS0/dataflow.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/debug_mgr.dat:system/vendor/camera/SOI20BS0/debug_mgr.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/exposure_ctrl.dat:system/vendor/camera/SOI20BS0/exposure_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/face_detector.dat:system/vendor/camera/SOI20BS0/face_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/flicker_detector.dat:system/vendor/camera/SOI20BS0/flicker_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/focus_stats_conv.dat:system/vendor/camera/SOI20BS0/focus_stats_conv.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/hal_ctrl.dat:system/vendor/camera/SOI20BS0/hal_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/hal_ctrl_platform.dat:system/vendor/camera/SOI20BS0/hal_ctrl_platform.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/hdr_comp.dat:system/vendor/camera/SOI20BS0/hdr_comp.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/idt_ctrl.dat:system/vendor/camera/SOI20BS0/idt_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/image_conv.dat:system/vendor/camera/SOI20BS0/image_conv.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/imgproc.dat:system/vendor/camera/SOI20BS0/imgproc.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/jpeg_enc.dat:system/vendor/camera/SOI20BS0/jpeg_enc.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/lens_ctrl.dat:system/vendor/camera/SOI20BS0/lens_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/module.dat:system/vendor/camera/SOI20BS0/module.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/motion_estimation.dat:system/vendor/camera/SOI20BS0/motion_estimation.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/multiframe_nr.dat:system/vendor/camera/SOI20BS0/multiframe_nr.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/object_tracker.dat:system/vendor/camera/SOI20BS0/object_tracker.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/scene_detector.dat:system/vendor/camera/SOI20BS0/scene_detector.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/snapshot_ctrl.dat:system/vendor/camera/SOI20BS0/snapshot_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0/streaming_ctrl.dat:system/vendor/camera/SOI20BS0/streaming_ctrl.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0_IMX200.dat:system/vendor/camera/SOI20BS0_IMX200.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0_BU64296GWX.dat:system/vendor/camera/SOI20BS0_BU64296GWX.dat \
    vendor/sony/amami/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/amami/proprietary/vendor/camera/jpeg_fsc.dat:system/vendor/camera/jpeg_fsc.dat \
    vendor/sony/amami/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat \
    vendor/sony/amami/proprietary/vendor/camera/product_CACAO.dat:system/vendor/camera/product_CACAO.dat \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_cam_ctrl_plugin.so:system/vendor/lib/camera/libexcal_cam_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_cap_ctrl_plugin.so:system/vendor/lib/camera/libexcal_cap_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_color_ctrl_plugin.so:system/vendor/lib/camera/libexcal_color_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_debug_display_plugin.so:system/vendor/lib/camera/libexcal_debug_display_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_exposure_ctrl_plugin.so:system/vendor/lib/camera/libexcal_exposure_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_face_detector_plugin.so:system/vendor/lib/camera/libexcal_face_detector_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_flicker_detector_plugin.so:system/vendor/lib/camera/libexcal_flicker_detector_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_focus_stats_conv_plugin.so:system/vendor/lib/camera/libexcal_focus_stats_conv_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_hal_ctrl_plugin.so:system/vendor/lib/camera/libexcal_hal_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_hdr_plugin.so:system/vendor/lib/camera/libexcal_hdr_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_idt_ctrl_plugin.so:system/vendor/lib/camera/libexcal_idt_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_image_conv_plugin.so:system/vendor/lib/camera/libexcal_image_conv_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_iq_ctrl_plugin.so:system/vendor/lib/camera/libexcal_iq_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_jpeg_enc_plugin.so:system/vendor/lib/camera/libexcal_jpeg_enc_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_lens_ctrl_plugin.so:system/vendor/lib/camera/libexcal_lens_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_motion_estimation_plugin.so:system/vendor/lib/camera/libexcal_motion_estimation_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_multiframe_nr_plugin.so:system/vendor/lib/camera/libexcal_multiframe_nr_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_object_tracker_plugin.so:system/vendor/lib/camera/libexcal_object_tracker_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_scene_detector_plugin.so:system/vendor/lib/camera/libexcal_scene_detector_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_snapshot_ctrl_plugin.so:system/vendor/lib/camera/libexcal_snapshot_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_splitter_plugin.so:system/vendor/lib/camera/libexcal_splitter_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/camera/libexcal_streaming_ctrl_plugin.so:system/vendor/lib/camera/libexcal_streaming_ctrl_plugin.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/sony/amami/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so

